language: python
python:
- '3.6'
sudo: false
cache: pip
install: pip install sphinx
script: sphinx-build -nWT -b html ./source/ ./build/html/
deploy:
  provider: s3
  access_key_id: 'AKIAY3FI6BUMTWD5ZZGL'
  secret_access_key:
    secure: AUXcAc5y2o/JryVMcQ9HYHOb3NyCwzPVLFtexqdFp48BUXom6b8mLivgRiB6bUQciMvUX7ujjUgBnYlQmXrPX7HAdX7aFcPM1EAXSmNjE6ztydIwNmQmXml6fPjYcTFlexNdkejnh6jlMEjaHXxRndEvOCM+hkcJheMvFxM40fiu4CJjOvoF75fklw8PnGpIqpAY29albmGDFrkI/bZ1kRRXf5hfhQ+w5trzRb3beDqlYSF0OU/vPUswx5pdFUbh8w20s3SWDXRxk67KLqK1L2kKtx+BJGyBWifv/eaTyvqhCyNVPukZrUFFnL8RfH6aU2/JmoCYdnpPyRi4z0sr6gNsKTtNJ71FoxBGfOx3g6v/FDvJl34QgEmtAnfWv30tF9HzujGJXoJf5myDPZI8oqd6DGGP0InBynrmAI1cxVrD6Tzb2IiYaOmDNec7/0qLNfb2Eb6sessYneywmZehO8CDauQuim9EdUNrnDktLkae64mSbCLTOIlfhWiNyGyjQq7oRSfRIXKHIE456B4jBlE2ly885E+44itS7QUfMaW8DT2hFF2iGa6caRApHpzBO/7272kW8UvaBwbb7qXpMLZXbOwT8kkf0p6+YHtHQmO624AY4zsZQN8ct0NWz+C/mIKJrDiFonM5kxKazKCoIzILmKsYthz+LnNRrgH6YOw=
  bucket: sphinx-test
  skip_cleanup: true
  local_dir: build/html
  region: "us-west-2"